// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB57ajcwAeqi3xPDBq1K461x0pyGyNJFF',
    appId: '1:689991533987:android:063879c965ec4f8a0d0616',
    messagingSenderId: '689991533987',
    projectId: 'ubuzima-connect-34fe9',
    storageBucket: 'ubuzima-connect-34fe9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAig3XVO18bHXe0bg3o8ICx59wkqqZOcBs',
    appId: '1:689991533987:ios:a629c17028c72d390d0616',
    messagingSenderId: '689991533987',
    projectId: 'ubuzima-connect-34fe9',
    storageBucket: 'ubuzima-connect-34fe9.firebasestorage.app',
    iosBundleId: 'com.example.ubuzimaConnect',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANJUXhUBEXzcZrul1Tef-ZcguX_LWXwpw',
    appId: '1:689991533987:web:827866044f6ac93a0d0616',
    messagingSenderId: '689991533987',
    projectId: 'ubuzima-connect-34fe9',
    storageBucket: 'ubuzima-connect-34fe9.firebasestorage.app',
  );
}
